# Site settings
baseURL = "https://vishnu.tech/"
languageCode = "en-US"
title = "Vishnu Mohandas"
theme = "hugo-split"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-118702537-1"

[params]

  # Metadata for search engines and social sharing
  name = "Vishnu Mohandas"
  description = "Make Happy."
  shareImage = "images/social.jpg"
  twitterHandle = "vishnukvmd"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2018 Vishnu Mohandas"

  # Section - Content
  [params.content]
    name = "Vishnu Mohandas"
    tagline = "Hacker. Musician. Product Guy."
    bio = "Born and brought up in [Kerala, India](https://www.google.co.in/search?q=kerala&tbm=isch).<br>Primarily a programmer, and self taught (/proclaimed) product manager. Spent the last 5 years building [Ringo](https://ringo.co), [Zeta](https://zeta.in) and [Kapow](https://kapow.games) at [Directi](https://directi.com).<br>Hobbies include fiddling with the violin, lurking on reddit and HN.<br>Influenced by Nick Bostrom's philosophies and Bo Burnham's comedy.<br>Currently figuring out life at New Delhi, India."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:me@vishnu.tech"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://linkedin.com/in/vishnukvmd/"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://facebook.com/vishnukvmd"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/vishnukvmd"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Other"

      [[params.links.list3.link]]
        text = "GitHub"
        url = "https://github.com/vishnukvmd"

	  [[params.links.list3.link]]
        text = "SoundCloud"
        url = "https://soundcloud.com/vishnukvmd"

      [[params.links.list3.link]]
        text = "XDA"
        url = "https://forum.xda-developers.com/member.php?u=4128904"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
